x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    logging: *default-logging

  dispatcher:
    image: semtech/mu-dispatcher:2.1.1
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    logging: *default-logging

  # Your extra services here
  resource:
    image: semtech/mu-cl-resources:1.27.2
    environment:
      CACHE_CLEAR_PATH: 'http://cache/.mu/clear-keys'
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.1.0
    links:
      - resource:backend
    labels:
      - 'logging=true'
    restart: always
    logging: *default-logging

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    logging: *default-logging

  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config/
    labels:
      - "logging=true"
    logging: *default-logging

  database:
    image: semtech/sparql-parser:0.0.15
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    labels:
      - "logging=true"
    logging: *default-logging

  triplestore:
    image: redpencil/virtuoso:1.4.0
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    logging: *default-logging

  frontend-dcat:
    image: lblod/frontend-decide-dcat:0.0.4
    labels:
      - 'logging=true'
    restart: always
    logging: *default-logging
  dcat:
    image: lblod/dcat-service:0.0.1
    logging: *default-logging
    labels:
      - logging=true
    restart: always

  #
  # LDES
  #
  ldes-client:
    image: lblod/ldes-client:0.0.5
    environment:
      WORKING_GRAPH: "http://mu.semte.ch/graphs/ldes/working-graph"
      RANDOMIZE_GRAPHS: true
      DIRECT_DATABASE_CONNECTION: http://triplestore:8890/sparql
      GRAPH_STORE_URL: http://triplestore:8890/sparql-graph-crud
      CRON_PATTERN: '* 23 * * * *' # Once per hour at HH:23
    volumes:
      - ./config/ldes-client:/config
